// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk2nQNorwJsNiuaab9EVyR7vN-PQic730',
    appId: '1:23121684195:web:28d80bfd7bc8562825c7d6',
    messagingSenderId: '23121684195',
    projectId: 'gen-lang-client-0543931071',
    authDomain: 'gen-lang-client-0543931071.firebaseapp.com',
    storageBucket: 'gen-lang-client-0543931071.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjAFvvLD6fzPUOtkbmRnWr3taKCpj1UIY',
    appId: '1:23121684195:android:2204f6f1e87f25ea25c7d6',
    messagingSenderId: '23121684195',
    projectId: 'gen-lang-client-0543931071',
    storageBucket: 'gen-lang-client-0543931071.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3IdHCWjKZhjcfR8mt6A2JJp5Zq-587b4',
    appId: '1:23121684195:ios:0fe2c04b35790dff25c7d6',
    messagingSenderId: '23121684195',
    projectId: 'gen-lang-client-0543931071',
    storageBucket: 'gen-lang-client-0543931071.firebasestorage.app',
    iosBundleId: 'com.example.medical',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3IdHCWjKZhjcfR8mt6A2JJp5Zq-587b4',
    appId: '1:23121684195:ios:0fe2c04b35790dff25c7d6',
    messagingSenderId: '23121684195',
    projectId: 'gen-lang-client-0543931071',
    storageBucket: 'gen-lang-client-0543931071.firebasestorage.app',
    iosBundleId: 'com.example.medical',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAk2nQNorwJsNiuaab9EVyR7vN-PQic730',
    appId: '1:23121684195:web:7ddefa4a6b36223025c7d6',
    messagingSenderId: '23121684195',
    projectId: 'gen-lang-client-0543931071',
    authDomain: 'gen-lang-client-0543931071.firebaseapp.com',
    storageBucket: 'gen-lang-client-0543931071.firebasestorage.app',
  );
}
